/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.valenbiciapiv2;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;


import com.mycompany.valenbiciapiv2.DatosJSon;
import java.awt.Color;
/**
 *
 * @author juanc
 */


public class ConexionBDD extends javax.swing.JFrame {

    private static Connection con;
    private static Statement s;
    private static DatosJSon dJSon;
    private static int numEst = 3;
    private static final String driver = "com.mysql.cj.jdbc.Driver";//com.mysql.jdbc.Driver";
    private static final String user = "";
    private static final String pass = "";
    private static final String url = "";
    /**
     * Creates new form ConexionBDD1
     */
//    public ConexionBDD() {
//        initComponents();
//    }
    
    public ConexionBDD(){
        initComponents();
        dJSon = new DatosJSon(numEst);  // Inicializa dJSon
        txtNumEstaciones.setText("" + numEst);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarConexion = new javax.swing.JButton();
        lblEstadoConexion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBoxListaDatos = new javax.swing.JTextArea();
        lblAddBDD = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumEstaciones = new javax.swing.JTextField();
        Datos = new javax.swing.JButton();
        lblDatosEstaciones = new javax.swing.JLabel();
        btnConectarBDD = new javax.swing.JButton();
        btnAddBDD = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCerrarConexion.setText("Cerrar conexión");
        btnCerrarConexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarConexionMouseClicked(evt);
            }
        });
        btnCerrarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarConexionActionPerformed(evt);
            }
        });

        lblEstadoConexion.setText("Estado de Conexión");

        txtBoxListaDatos.setColumns(20);
        txtBoxListaDatos.setRows(5);
        jScrollPane1.setViewportView(txtBoxListaDatos);

        lblAddBDD.setText("Estado Adicción");

        jLabel1.setText("Introduce el numero de estaciones a consultar:");

        txtNumEstaciones.setText("Num Estaciones");
        txtNumEstaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumEstacionesFocusLost(evt);
            }
        });

        Datos.setText("Datos");
        Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatosMouseClicked(evt);
            }
        });
        Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosActionPerformed(evt);
            }
        });

        lblDatosEstaciones.setText("Obtener datos de Estaciones");

        btnConectarBDD.setText("Conectar");
        btnConectarBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConectarBDDMouseClicked(evt);
            }
        });
        btnConectarBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarBDDActionPerformed(evt);
            }
        });

        btnAddBDD.setText("Añadir a BDD");
        btnAddBDD.setEnabled(false);
        btnAddBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddBDDMouseClicked(evt);
            }
        });

        jButton1.setText("Es");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("En");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addComponent(txtNumEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnConectarBDD)
                                    .addComponent(Datos))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnCerrarConexion)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAddBDD)
                                                .addComponent(lblEstadoConexion))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addComponent(lblDatosEstaciones))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnAddBDD))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Datos)
                    .addComponent(lblDatosEstaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConectarBDD)
                    .addComponent(lblEstadoConexion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBDD)
                    .addComponent(lblAddBDD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarConexion)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void conector(){
        try{
            con = DriverManager.getConnection(url, user, pass);
            
            if(btnConectarBDD.getText()=="Connect"){
            
                lblEstadoConexion.setText("Successful Connection");
            }
            else{
                lblEstadoConexion.setText("Conexión Exitosa");
            }
            
            lblEstadoConexion.setBackground(Color.green);
            
        }
        catch(SQLException ex){
            lblEstadoConexion.setText("Error: " + ex.getMessage());
            lblEstadoConexion.setBackground(Color.red);
        }
    
    }
    private void btnCerrarConexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarConexionMouseClicked
        try{
            con.close();
            lblEstadoConexion.setText("Desconectado de la Base de datos.");
        }catch(SQLException ex){
            Logger.getLogger(ConexionBDD.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnCerrarConexionMouseClicked

    private void btnCerrarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarConexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarConexionActionPerformed

    private void txtNumEstacionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumEstacionesFocusLost
        numEst= Integer.parseInt(txtNumEstaciones.getText());
        dJSon.mostrarDatos(numEst);
        lblDatosEstaciones.setText("Datos estaciones:");
        txtBoxListaDatos.setText(dJSon.getDatos());
    }//GEN-LAST:event_txtNumEstacionesFocusLost

    private void DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatosMouseClicked
        
        
        dJSon.mostrarDatos(numEst);
        lblDatosEstaciones.setText("Datos de estaciones:");
        txtBoxListaDatos.setText(dJSon.getDatos());
    }//GEN-LAST:event_DatosMouseClicked

    private void DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatosActionPerformed

    private void btnConectarBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConectarBDDMouseClicked
        conector();
        btnAddBDD.setEnabled(true);

    }//GEN-LAST:event_btnConectarBDDMouseClicked

    private void btnConectarBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarBDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConectarBDDActionPerformed

    private void btnAddBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBDDMouseClicked
        try{
            
            
            for(int i=0;i<numEst;i++){
                
                String sql = " insert into historico (estacion_id,direccion,bicis_disponibles,anclajes_libres,estado_operativo,fecha_registro,latitud,longitud)"
                        + "values ( "+dJSon.estacion_id[i]+",'"+dJSon.direccion[i]+"',"+dJSon.bicis_disponibles[i]
                        + ","+dJSon.anclajes_libres[i]+","+dJSon.estado_operativo[i]+ ",STR_TO_DATE('"+dJSon.fecha_registro[i]+"','%d/%m/%Y %H:%i:%s')"
                        + ","+dJSon.puntoA[i]+","+dJSon.puntoB[i]+");";
                System.out.println(sql);
                Statement stmt = con.createStatement();
                stmt.executeUpdate(sql);
            }
            if(Datos.getText() =="Datos")
            {
                lblAddBDD.setText("Datos añadidos.");
            }
            else{
                lblAddBDD.setText("Added data.");
            }
            
        }
        catch(SQLException e){
            lblAddBDD.setText("Error de conexión "+e.getMessage());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAddBDDMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jLabel1.setText("Enter the number of stations to query:" );
       Datos.setText("Dates");
       lblDatosEstaciones.setText("Get data from stations");
       btnConectarBDD.setText("Connect");
       lblEstadoConexion.setText("Connection status");
       btnAddBDD.setText("Add to DB");
       lblAddBDD.setText("Addition status");
       btnCerrarConexion.setText("Close connection");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel1.setText("Introduce el numero de estaciones a consultar:" );
       Datos.setText("Datos");
       lblDatosEstaciones.setText("Obtener datos de Estaciones");
       btnConectarBDD.setText("Conectar");
       lblEstadoConexion.setText("Estado de conexión");
       btnAddBDD.setText("Añadir a BDD");
       lblAddBDD.setText("Estado de Adicción");
       btnCerrarConexion.setText("Cerrar Conexión");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexionBDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Datos;
    private javax.swing.JButton btnAddBDD;
    private javax.swing.JButton btnCerrarConexion;
    private javax.swing.JButton btnConectarBDD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddBDD;
    private javax.swing.JLabel lblDatosEstaciones;
    private javax.swing.JLabel lblEstadoConexion;
    private javax.swing.JTextArea txtBoxListaDatos;
    private javax.swing.JTextField txtNumEstaciones;
    // End of variables declaration//GEN-END:variables
}
